const audio=document.getElementById("audio"),stationList=document.getElementById("stationList"),stationSearch=document.getElementById("stationSearch"),countrySearch=document.getElementById("countrySearch"),countryList=document.getElementById("countryList"),countryToggle=document.getElementById("countryToggle"),countryPanel=document.getElementById("countryPanel"),stationName=document.getElementById("stationName"),stationCountry=document.getElementById("stationCountry"),subtitle=document.getElementById("subtitle"),statusEl=document.getElementById("status"),favBtn=document.getElementById("favBtn"),favoritesOnlyBtn=document.getElementById("favoritesOnly");
const BASES=["https://de1.api.radio-browser.info/json","https://nl1.api.radio-browser.info/json","https://at1.api.radio-browser.info/json"];
let selectedCountry="Nederland",currentStation=null,favoritesOnly=false,favorites=JSON.parse(localStorage.getItem("favorites")||"[]"),stationsByCountry={"Nederland":[...DEFAULT_STATIONS]},loadingCountry=false,countriesLoaded=false;
function saveFavorites(){localStorage.setItem("favorites",JSON.stringify(favorites))}
function isFav(n){return favorites.includes(n)}
function niceName(n){const m={"Netherlands":"Nederland","Belgium":"België","Germany":"Duitsland","France":"Frankrijk","United Kingdom":"Verenigd Koninkrijk","United States":"Verenigde Staten","Spain":"Spanje","Italy":"Italië","Switzerland":"Zwitserland","Austria":"Oostenrijk","Sweden":"Zweden","Norway":"Noorwegen","Denmark":"Denemarken","Turkey":"Turkije","Morocco":"Marokko","Brazil":"Brazilië","Japan":"Japan","South Korea":"Zuid-Korea","South Africa":"Zuid-Afrika","Greece":"Griekenland","Ukraine":"Oekraïne","Czech Republic":"Tsjechië","Indonesia":"Indonesië"};return m[n]||n}
async function fetchJson(path){let e;for(const b of BASES){try{const r=await fetch(b+path,{cache:"no-store"});if(!r.ok)throw Error(r.status);return await r.json()}catch(err){e=err}}throw e}
async function loadCountries(){if(countriesLoaded)return;try{statusEl.textContent="Landen laden...";const data=await fetchJson("/countries?hidebroken=true&order=stationcount&reverse=true");const map={"Nederland":"NL"};data.filter(c=>c.iso_3166_1&&c.name&&c.stationcount>0).forEach(c=>map[niceName(c.name)]=c.iso_3166_1);COUNTRY_CODES=map;countriesLoaded=true;statusEl.textContent="Landen geladen"}catch(e){statusEl.textContent="Landen laden lukte niet"}renderCountries()}
function countries(){return Object.keys(COUNTRY_CODES).sort((a,b)=>a==="Nederland"?-1:b==="Nederland"?1:a.localeCompare(b,"nl"))}
async function fetchCountryStations(country){if(stationsByCountry[country])return stationsByCountry[country];const code=COUNTRY_CODES[country];if(!code)return[];loadingCountry=true;statusEl.textContent=`Zenders laden voor ${country}...`;renderStations();try{const data=await fetchJson(`/stations/bycountrycodeexact/${code}?hidebroken=true&order=clickcount&reverse=true&limit=160`);const seen=new Set();let stations=data.filter(s=>s.name&&(s.url_resolved||s.url)).map(s=>({name:s.name.trim(),url:String(s.url_resolved||s.url).replace("http://","https://"),country,tags:s.tags||""})).filter(s=>{const k=(s.name+"|"+s.url).toLowerCase();if(seen.has(k))return false;seen.add(k);return true});if(country==="Nederland"){const d=[...DEFAULT_STATIONS],keys=new Set(d.map(s=>s.name.toLowerCase()));stations.forEach(s=>{if(!keys.has(s.name.toLowerCase()))d.push(s)});stations=d}stationsByCountry[country]=stations;statusEl.textContent=`${stations.length} zenders geladen voor ${country}`}catch(e){stationsByCountry[country]=country==="Nederland"?[...DEFAULT_STATIONS]:[];statusEl.textContent=`Zenders laden voor ${country} lukte niet`}finally{loadingCountry=false;renderStations()}return stationsByCountry[country]}
function allKnownStations(){const map=new Map();Object.values(stationsByCountry).flat().forEach(s=>map.set((s.name+"|"+s.url).toLowerCase(),s));return[...map.values()]}
function renderCountries(){const q=countrySearch.value.trim().toLowerCase();countryList.innerHTML="";countries().filter(c=>c.toLowerCase().includes(q)).forEach(country=>{const btn=document.createElement("button");btn.className="country-item"+(country===selectedCountry?" active":"");btn.textContent=country;btn.onclick=async()=>{selectedCountry=country;countryToggle.textContent=`${country} ▾`;countryPanel.classList.add("hidden");await fetchCountryStations(country);renderStations()};countryList.appendChild(btn)})}
function filteredStations(){const q=stationSearch.value.trim().toLowerCase();const src=q?allKnownStations():(stationsByCountry[selectedCountry]||[]);return src.filter(s=>(!favoritesOnly||isFav(s.name))&&(!q||`${s.name} ${s.country} ${s.tags||""}`.toLowerCase().includes(q)))}
function renderStations(){stationList.innerHTML="";if(loadingCountry){stationList.innerHTML='<p class="status">Zenders worden geladen...</p>';return}const q=stationSearch.value.trim(),list=filteredStations();if(!list.length){stationList.innerHTML='<p class="status">Geen zenders gevonden</p>';return}list.forEach(station=>{const btn=document.createElement("button");btn.className="station-item"+(currentStation?.name===station.name?" active":"");btn.innerHTML=`<span>${station.name}</span>${q?`<small>${station.country}</small>`:""}`;btn.onclick=()=>selectStation(station);stationList.appendChild(btn)})}
function selectStation(station){currentStation=station;audio.src=station.url;stationName.textContent=station.name;stationCountry.textContent=station.country;subtitle.textContent=`${station.country} • online radio`;updateFavButton();renderStations();statusEl.textContent="Zender geselecteerd"}
function updateFavButton(){const a=currentStation&&isFav(currentStation.name);favBtn.textContent=a?"♥":"♡";favBtn.classList.toggle("active",!!a)}
document.getElementById("playBtn").onclick=async()=>{if(!currentStation){const f=filteredStations()[0];if(f)selectStation(f)}try{await audio.play();statusEl.textContent="Speelt af"}catch(e){statusEl.textContent="Afspelen lukte niet. Kies eventueel een andere zender."}};
document.getElementById("stopBtn").onclick=()=>{audio.pause();audio.currentTime=0;statusEl.textContent="Gestopt"};
favBtn.onclick=()=>{if(!currentStation)return;if(isFav(currentStation.name))favorites=favorites.filter(f=>f!==currentStation.name);else favorites.push(currentStation.name);saveFavorites();updateFavButton();renderStations()};
favoritesOnlyBtn.onclick=()=>{favoritesOnly=!favoritesOnly;favoritesOnlyBtn.textContent=favoritesOnly?"Alle zenders bekijken":"♡ Favorieten bekijken";renderStations()};
countryToggle.onclick=()=>{countryPanel.classList.toggle("hidden");loadCountries();renderCountries()};
stationSearch.oninput=renderStations;countrySearch.oninput=renderCountries;renderCountries();fetchCountryStations("Nederland").then(renderStations);loadCountries();
