const audio=document.getElementById("audio"),stationList=document.getElementById("stationList"),stationSearch=document.getElementById("stationSearch"),countrySearch=document.getElementById("countrySearch"),countryList=document.getElementById("countryList"),countryToggle=document.getElementById("countryToggle"),countryPanel=document.getElementById("countryPanel"),stationName=document.getElementById("stationName"),stationCountry=document.getElementById("stationCountry"),subtitle=document.getElementById("subtitle"),statusEl=document.getElementById("status"),favBtn=document.getElementById("favBtn"),favoritesOnlyBtn=document.getElementById("favoritesOnly"),volume=document.getElementById("volume");
let selectedCountry="Nederland",currentStation=null,favoritesOnly=false,favorites=JSON.parse(localStorage.getItem("favorites")||"[]");
function countries(){return[...new Set(STATIONS.map(s=>s.country))].sort((a,b)=>a==="Nederland"?-1:b==="Nederland"?1:a.localeCompare(b,"nl"))}
function saveFavorites(){localStorage.setItem("favorites",JSON.stringify(favorites))}
function isFav(n){return favorites.includes(n)}
function renderCountries(){const q=countrySearch.value.trim().toLowerCase();countryList.innerHTML="";countries().filter(c=>c.toLowerCase().includes(q)).forEach(country=>{const btn=document.createElement("button");btn.className="country-item"+(country===selectedCountry?" active":"");btn.textContent=country;btn.onclick=()=>{selectedCountry=country;countryToggle.textContent=`${country} ▾`;countryPanel.classList.add("hidden");renderStations()};countryList.appendChild(btn)})}
function filteredStations(){const q=stationSearch.value.trim().toLowerCase();return STATIONS.filter(s=>{const countryOk=q?true:s.country===selectedCountry;const favOk=!favoritesOnly||isFav(s.name);const queryOk=!q||`${s.name} ${s.country}`.toLowerCase().includes(q);return countryOk&&favOk&&queryOk})}
function renderStations(){stationList.innerHTML="";const q=stationSearch.value.trim();const list=filteredStations();if(!list.length){stationList.innerHTML='<p class="status">Geen zenders gevonden</p>';return}list.forEach(station=>{const btn=document.createElement("button");btn.className="station-item"+(currentStation?.name===station.name?" active":"");btn.innerHTML=`<span>${station.name}</span>${q?`<small>${station.country}</small>`:""}`;btn.onclick=()=>selectStation(station);stationList.appendChild(btn)})}
function selectStation(station){currentStation=station;audio.src=station.url;stationName.textContent=station.name;stationCountry.textContent=station.country;subtitle.textContent=`${station.country} • online radio`;updateFavButton();renderStations();statusEl.textContent="Zender geselecteerd"}
function updateFavButton(){const active=currentStation&&isFav(currentStation.name);favBtn.textContent=active?"♥":"♡";favBtn.classList.toggle("active",!!active)}
document.getElementById("playBtn").onclick=async()=>{if(!currentStation){const first=filteredStations()[0];if(first)selectStation(first)}try{await audio.play();statusEl.textContent="Speelt af"}catch(e){statusEl.textContent="Afspelen lukte niet. Kies eventueel een andere zender."}};
document.getElementById("stopBtn").onclick=()=>{audio.pause();audio.currentTime=0;statusEl.textContent="Gestopt"};
favBtn.onclick=()=>{if(!currentStation)return;if(isFav(currentStation.name)){favorites=favorites.filter(f=>f!==currentStation.name)}else{favorites.push(currentStation.name)}saveFavorites();updateFavButton();renderStations()};
favoritesOnlyBtn.onclick=()=>{favoritesOnly=!favoritesOnly;favoritesOnlyBtn.textContent=favoritesOnly?"Alle zenders bekijken":"♡ Favorieten bekijken";renderStations()};
volume.oninput=()=>audio.volume=Number(volume.value);
countryToggle.onclick=()=>{countryPanel.classList.toggle("hidden");renderCountries()};
stationSearch.oninput=renderStations;countrySearch.oninput=renderCountries;
if("serviceWorker"in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"))}
audio.volume=Number(volume.value);renderCountries();renderStations();
